const nodemailer = require('nodemailer');
const config = require('../config/env');

const createTransporter = () => {
  return nodemailer.createTransport({
    host: config.smtp.host,
    port: config.smtp.port,
    secure: false,
    auth: {
      user: config.smtp.user,
      pass: config.smtp.pass,
    },
  });
};

const sendInvoiceEmail = async (invoiceData, pdfBuffer) => {
  if (!config.smtp.host || !config.smtp.user || !config.smtp.pass) {
    throw new Error('SMTP configuration is incomplete.');
  }

  const transporter = createTransporter();

  const mailOptions = {
    from: config.smtp.from,
    to: invoiceData.vendor_email,
    subject: `Invoice ${invoiceData.invoice_number} from VendorBridge`,
    html: `
      <div style="font-family: 'Segoe UI', Tahoma, sans-serif; max-width: 600px; margin: 0 auto;">
        <div style="background: linear-gradient(135deg, #6366f1, #8b5cf6); padding: 32px; border-radius: 12px 12px 0 0;">
          <h1 style="color: white; margin: 0; font-size: 24px;">VendorBridge</h1>
          <p style="color: rgba(255,255,255,0.8); margin: 4px 0 0;">Invoice Notification</p>
        </div>
        <div style="padding: 32px; background: #f8fafc; border: 1px solid #e2e8f0; border-top: none; border-radius: 0 0 12px 12px;">
          <p style="color: #1e293b; font-size: 16px;">Dear ${invoiceData.vendor_contact || invoiceData.vendor_name},</p>
          <p style="color: #475569;">Please find attached the invoice for your recent purchase order.</p>
          <div style="background: white; border-radius: 8px; padding: 20px; margin: 20px 0; border: 1px solid #e2e8f0;">
            <table style="width: 100%; border-collapse: collapse;">
              <tr><td style="color: #64748b; padding: 6px 0;">Invoice Number</td><td style="font-weight: 600; text-align: right;">${invoiceData.invoice_number}</td></tr>
              <tr><td style="color: #64748b; padding: 6px 0;">PO Number</td><td style="font-weight: 600; text-align: right;">${invoiceData.po_number}</td></tr>
              <tr><td style="color: #64748b; padding: 6px 0;">Amount</td><td style="font-weight: 700; text-align: right; color: #6366f1; font-size: 18px;">₹${parseFloat(invoiceData.total_amount).toLocaleString('en-IN', { minimumFractionDigits: 2 })}</td></tr>
              <tr><td style="color: #64748b; padding: 6px 0;">Due Date</td><td style="font-weight: 600; text-align: right;">${invoiceData.due_date ? new Date(invoiceData.due_date).toLocaleDateString('en-IN') : 'N/A'}</td></tr>
            </table>
          </div>
          <p style="color: #475569; font-size: 14px;">Payment Terms: ${invoiceData.payment_terms || 'Net 30'}</p>
          <p style="color: #94a3b8; font-size: 12px; margin-top: 24px; border-top: 1px solid #e2e8f0; padding-top: 16px;">
            This invoice was generated by VendorBridge ERP. If you have any questions, please contact your procurement officer.
          </p>
        </div>
      </div>
    `,
    attachments: [
      {
        filename: `${invoiceData.invoice_number}.pdf`,
        content: pdfBuffer,
        contentType: 'application/pdf',
      },
    ],
  };

  await transporter.sendMail(mailOptions);
  console.log(`✅ Invoice email sent to ${invoiceData.vendor_email}`);
};

module.exports = { sendInvoiceEmail };
